### PR TITLE
Github actions: Release action to make PRs to the release branch

### PR DESCRIPTION
**Pull request by mpellicer**
Now this is in CF it's great to have this action to make releases.

### CODE REVIEW

**Comment by mpellicer** [comment]
Something not great is that we're exposing our Github actions in Cloudflare.

https://e99ef0fa.login-canvas-ox-ac-uk.pages.dev/.github/workflows/release.yml

I'm not sure about serving the .git folder tho, I think cloudflare does not serve it

https://e99ef0fa.login-canvas-ox-ac-uk.pages.dev/.git/config

**Comment by buckett** [comment]
Nice spot, I'd be tempted to add a simple build process.
We could also then get automatic cache invalidation for JS/CSS.

What do you think?

**Comment by buckett** [comment]
You can see the uploaded asset in https://dash.cloudflare.com/1adb0f307cf4b14f583113668c4cd5fa/pages/view/login-canvas-ox-ac-uk/e99ef0fa-5059-4a5f-b207-7b03d458d507/files and it doesn't include the .git folder.

**Comment by mpellicer** [comment]
> Nice spot, I'd be tempted to add a simple build process. We could also then get automatic cache invalidation for JS/CSS.
> 
> What do you think?

Desirable for sure.

**Comment by mpellicer** [comment]
I'm wondering if we still need the /beta and /test folders now we have CF ? The only difference I see is the Canvas URL?

**Comment by buckett** [comment]
> I'm wondering if we still need the /beta and /test folders now we have CF ? The only difference I see is the Canvas URL?

Yeah, I think they can go.

**Review by buckett — APPROVED** [review]

**Pull request merged**
