### PR TITLE
AB#70102 Migration from AWS S3 to Cloudflare

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Review by buckett — COMMENTED** [review]
I think we want a 404.html file to indicate this isn't a SPA.

**Comment by mpellicer** [comment]
> 


> I think we want a 404.html file to indicate this isn't a SPA.

Sure, it can be an empty file right?

**Review by buckett — APPROVED** [review]
I'd have been tempted to put something into the 404 pages just so it's more obvious what's wrong rather than relying on browsers own message, but fine as is.

**Comment by mpellicer** [comment]
Thanks for the review!

**Pull request merged**
