### PR TITLE
LDP-11 Update privacy hyperlink

### PR DESCRIPTION
**Pull request by sebastianchristopher**

### CODE REVIEW

**Review by buckett — COMMENTED** [review]
Change looks fine, but do you also want to update the beta/test versions as well?

**Comment by nicholaswilson100** [comment]
Fast work Chris! Good stuff!

**Comment by nicholaswilson100** [comment]
If you want to be super process-following, then, as per this page https://wiki.it.ox.ac.uk/weblearn/CanvasDiscoveryPage, you can make the change to test and beta, deploy it, check it works okay on test/beta, and then after a successful test, make the change and deploy it to production.

**Comment by buckett** [comment]
Nice one.

**Pull request merged**
